**A place to organize and tidy up user data stored in (sign_up_system/user_data/user_data.csv file)**

    Read csv file and show the data frame

In [82]:
# importing dependencies
import pandas as pd

In [83]:
# read user_data.csv
user_df = pd.read_csv("template_data.csv")
# show the data frame
user_df

,Full name,Gender,Date of birth,Email,Password
0,Avery Brooks,Prefer not to say,1997-02-11,avery.b97@gmail.com,ab97
1,Daniel Carter,Male,2003-09-04,daniel.c03@yahoo.com,dc03
2,Olivia Turner,Female,1989-06-27,olivia.t89@email.com,ot89
3,Lucas Evans,Male,1995-12-19,lucas.e95@gmail.com,le95
4,Mia Bennett,Female,2001-03-08,mia.b01@yahoo.com,mb01
...,...,...,...,...,...
88,Kylie Schultz,Female,1990-09-29,kylie.s90@yahoo.com,ks90
89,Zane Harper,Male,1997-06-02,zane.h97@email.com,zh97
90,Molly Bates,Female,2004-05-23,molly.b04@gmail.com,mb04
91,Grant Norris,Male,1992-12-18,grant.n92@yahoo.com,gn92
92,Eliza Lowe,Prefer not to say,2000-08-04,eliza.l00@email.com,el00

    Find specific data

    - Show first 3 users and last 3 users

In [84]:
# show first 3 users
user_df.head(3)

,Full name,Gender,Date of birth,Email,Password
0,Avery Brooks,Prefer not to say,1997-02-11,avery.b97@gmail.com,ab97
1,Daniel Carter,Male,2003-09-04,daniel.c03@yahoo.com,dc03
2,Olivia Turner,Female,1989-06-27,olivia.t89@email.com,ot89

In [85]:
# show last 3 users
user_df.tail(3)

,Full name,Gender,Date of birth,Email,Password
90,Molly Bates,Female,2004-05-23,molly.b04@gmail.com,mb04
91,Grant Norris,Male,1992-12-18,grant.n92@yahoo.com,gn92
92,Eliza Lowe,Prefer not to say,2000-08-04,eliza.l00@email.com,el00

    - Find specific users by Gender

- Male Gender

In [86]:
# find specific data (Gender = male)
male_user_df = user_df[user_df['Gender'] == "Male"]
male_user_df

           Full name Gender Date of birth                   Email Password
1      Daniel Carter   Male    2003-09-04    daniel.c03@yahoo.com     dc03
3        Lucas Evans   Male    1995-12-19     lucas.e95@gmail.com     le95
5        Henry Scott   Male    1992-08-14     henry.s92@email.com     hs92
7       Ethan Rivera   Male    1987-04-22     ethan.r87@yahoo.com     er87
9        Jack Nelson   Male    2002-07-05      jack.n02@gmail.com     jn02
11     Noah Mitchell   Male    1986-05-03      noah.m86@email.com     nm86
13        Ryan Baker   Male    1994-06-11      ryan.b94@yahoo.com     rb94
15     Benjamin Ward   Male    1998-09-26  benjamin.w98@gmail.com     bw98
17       Owen Torres   Male    1990-03-21      owen.t90@email.com     ot90
19        Caleb Reed   Male    1988-11-07     caleb.r88@yahoo.com     cr88
21       Logan Price   Male    2002-04-10     logan.p02@gmail.com     lp02
23      Isaac Flores   Male    1985-09-01     isaac.f85@email.com     if85
25        David Gray   Male    1997-01-12     david.g97@yahoo.com     dg97
27      Joseph Perry   Male    1991-05-19    joseph.p91@gmail.com     jp91
29     Andrew Butler   Male    2004-02-03    andrew.b04@email.com     ab04
31      Wyatt Foster   Male    2001-07-31     wyatt.f01@yahoo.com     wf01
33  Julian Alexander   Male    1999-12-14    julian.a99@gmail.com     ja99
35    Connor Griffin   Male    2003-03-06    connor.g03@email.com     cg03
37      Nathan Woods   Male    1998-08-08    nathan.w98@yahoo.com     nw98
39      Aaron Jordan   Male    1986-12-27     aaron.j86@gmail.com     aj86
41    Isaiah Chapman   Male    1993-03-30    isaiah.c93@email.com     ic93
43      Evan Elliott   Male    1990-07-13      evan.e90@yahoo.com     ee90
45     Jordan Rhodes   Male    1996-02-01    jordan.r96@gmail.com     jr96
47       Robert Cole   Male    1988-04-17    robert.c88@email.com     rc88
49       Miles Stone   Male    2000-10-26     miles.s00@yahoo.com     ms00
51         Leo Burns   Male    1992-01-24       leo.b92@gmail.com     lb92
53    Nathan Holland   Male    1989-03-14    nathan.h89@email.com     nh89
55       Ian Simpson   Male    1994-08-23       ian.s94@yahoo.com     is94
57       Adam Porter   Male    1987-11-02      adam.p87@gmail.com     ap87
59         Eli Hicks   Male    2000-07-15       eli.h00@email.com     eh00
61       Jason Henry   Male    1996-05-12     jason.h96@yahoo.com     jh96
63       Blake Mason   Male    1993-09-21     blake.m93@gmail.com     bm93
65       Tyler Dixon   Male    1985-07-28     tyler.d85@email.com     td85
67     Cole Ferguson   Male    1990-12-05      cole.f90@yahoo.com     cf90
69    Brandon Greene   Male    1997-03-25   brandon.g97@gmail.com     bg97
71       Derek Payne   Male    1986-06-30     derek.p86@email.com     dp86
73      Sean Spencer   Male    2002-10-01      sean.s02@yahoo.com     ss02
75       Trevor Long   Male    1999-05-16    trevor.l99@gmail.com     tl99
77      Gavin Palmer   Male    1991-01-06     gavin.p91@email.com     gp91
79     Marcus Sutton   Male    1988-08-19    marcus.s88@yahoo.com     ms88
81      Colin Reeves   Male    1993-02-27     colin.r93@gmail.com     cr93
83       Dean Larson   Male    1994-11-04      dean.l94@email.com     dl94
85      Spencer Dean   Male    1987-10-15   spencer.d87@yahoo.com     sd87
87    Tristan Newman   Male    2002-03-12   tristan.n02@gmail.com     tn02
89       Zane Harper   Male    1997-06-02      zane.h97@email.com     zh97
91      Grant Norris   Male    1992-12-18     grant.n92@yahoo.com     gn92

In [87]:
# find the number of user with Male gender
print(f"Data Frame size : {male_user_df.shape}")
print(f"Number of Male users : {male_user_df.shape[0]}")

Data Frame size : (46, 5)
Number of Male users : 46

- Female Gender

In [88]:
# find specific data (Gender = female)
female_user_df = user_df[user_df['Gender'] == "Female"]
female_user_df

           Full name  Gender Date of birth                   Email Password
2      Olivia Turner  Female    1989-06-27    olivia.t89@email.com     ot89
4        Mia Bennett  Female    2001-03-08       mia.b01@yahoo.com     mb01
8       Sophia Green  Female    1999-01-17    sophia.g99@email.com     sg99
10       Ella Parker  Female    1991-10-09      ella.p91@yahoo.com     ep91
12     Grace Collins  Female    2000-02-28     grace.c00@gmail.com     gc00
16       Lily Cooper  Female    2001-08-13      lily.c01@yahoo.com     lc01
18      Hannah Kelly  Female    2004-05-17    hannah.k04@gmail.com     hk04
20       Aria Watson  Female    1996-07-29      aria.w96@email.com     aw96
22      Scarlett Cox  Female    1993-02-15  scarlett.c93@yahoo.com     sc93
26     Emily Sanders  Female    2003-10-28     emily.s03@email.com     es03
28  Victoria Russell  Female    1989-08-06  victoria.r89@yahoo.com     vr89
30   Madison Simmons  Female    1995-11-25   madison.s95@gmail.com     ms95
34    Penelope Hayes  Female    1987-06-18  penelope.h87@yahoo.com     ph87
36      Lucy Wallace  Female    1994-10-22      lucy.w94@gmail.com     lw94
40      Stella Owens  Female    2002-09-16    stella.o02@yahoo.com     so02
42      Bella Knight  Female    2001-05-05     bella.k01@gmail.com     bk01
46   Sadie Armstrong  Female    2003-11-11     sadie.a03@yahoo.com     sa03
48      Alice Pierce  Female    1997-09-03     alice.p97@gmail.com     ap97
52        Eva Powell  Female    2002-12-19       eva.p02@yahoo.com     ep02
54        Clara Webb  Female    2001-04-01     clara.w01@gmail.com     cw01
56       Rose Tucker  Female    2003-06-07      rose.t03@email.com     rt03
58   Madeline Hunter  Female    1999-02-18  madeline.h99@yahoo.com     mh99
62       Sophie Boyd  Female    2004-03-09    sophie.b04@email.com     sb04
64     Claire Warren  Female    2002-02-06    claire.w02@yahoo.com     cw02
66        Elena Shaw  Female    1998-11-13     elena.s98@gmail.com     es98
68      Ruby Nichols  Female    2001-01-20      ruby.n01@email.com     rn01
72       Faith Grant  Female    1995-04-14     faith.g95@gmail.com     fg95
74      Luna Hawkins  Female    1992-07-07      luna.h92@email.com     lh92
78        Jade Black  Female    2000-12-08      jade.b00@gmail.com     jb00
80     Tessa Gregory  Female    1996-03-11     tessa.g96@email.com     tg96
82    Vanessa Little  Female    2003-07-30   vanessa.l03@yahoo.com     vl03
84       Hope Fuller  Female    2001-06-21      hope.f01@gmail.com     hf01
86       Brooke Carr  Female    1998-01-08    brooke.c98@email.com     bc98
88     Kylie Schultz  Female    1990-09-29     kylie.s90@yahoo.com     ks90
90       Molly Bates  Female    2004-05-23     molly.b04@gmail.com     mb04

In [89]:
# find the number of Female user
print(f"Data Frame size : {female_user_df.shape}")
print(f"Number Female users : {female_user_df.shape[0]}")

Data Frame size : (35, 5)
Number Female users : 35

    Find specific users by year of birth

- Male users that born < 2000-12-31

In [90]:
# find male users with born year < 2000-12-31
under_twoth_male = male_user_df[male_user_df['Date of birth'] < '2000-12-31']
print("Male user that born under < 2000-12-31\n")
print(under_twoth_male)
# Number of male users that born < 2000-12-31
print("="*75)
print(f"\nTotal : {under_twoth_male.shape[0]}")

Male user that born under < 2000-12-31

           Full name Gender Date of birth                   Email Password
3        Lucas Evans   Male    1995-12-19     lucas.e95@gmail.com     le95
5        Henry Scott   Male    1992-08-14     henry.s92@email.com     hs92
7       Ethan Rivera   Male    1987-04-22     ethan.r87@yahoo.com     er87
11     Noah Mitchell   Male    1986-05-03      noah.m86@email.com     nm86
13        Ryan Baker   Male    1994-06-11      ryan.b94@yahoo.com     rb94
15     Benjamin Ward   Male    1998-09-26  benjamin.w98@gmail.com     bw98
17       Owen Torres   Male    1990-03-21      owen.t90@email.com     ot90
19        Caleb Reed   Male    1988-11-07     caleb.r88@yahoo.com     cr88
23      Isaac Flores   Male    1985-09-01     isaac.f85@email.com     if85
25        David Gray   Male    1997-01-12     david.g97@yahoo.com     dg97
27      Joseph Perry   Male    1991-05-19    joseph.p91@gmail.com     jp91
33  Julian Alexander   Male    1999-12-14    julian.a99@gmail.com     ja99
37      Nathan Woods   Male    1998-08-08    nathan.w98@yahoo.com     nw98
39      Aaron Jordan   Male    1986-12-27     aaron.j86@gmail.com     aj86
41    Isaiah Chapman   Male    1993-03-30    isaiah.c93@email.com     ic93
43      Evan Elliott   Male    1990-07-13      evan.e90@yahoo.com     ee90
45     Jordan Rhodes   Male    1996-02-01    jordan.r96@gmail.com     jr96
47       Robert Cole   Male    1988-04-17    robert.c88@email.com     rc88
49       Miles Stone   Male    2000-10-26     miles.s00@yahoo.com     ms00
51         Leo Burns   Male    1992-01-24       leo.b92@gmail.com     lb92
53    Nathan Holland   Male    1989-03-14    nathan.h89@email.com     nh89
55       Ian Simpson   Male    1994-08-23       ian.s94@yahoo.com     is94
57       Adam Porter   Male    1987-11-02      adam.p87@gmail.com     ap87
59         Eli Hicks   Male    2000-07-15       eli.h00@email.com     eh00
61       Jason Henry   Male    1996-05-12     jason.h96@yahoo.com     jh96
63       Blake Mason   Male    1993-09-21     blake.m93@gmail.com     bm93
65       Tyler Dixon   Male    1985-07-28     tyler.d85@email.com     td85
67     Cole Ferguson   Male    1990-12-05      cole.f90@yahoo.com     cf90
69    Brandon Greene   Male    1997-03-25   brandon.g97@gmail.com     bg97
71       Derek Payne   Male    1986-06-30     derek.p86@email.com     dp86
75       Trevor Long   Male    1999-05-16    trevor.l99@gmail.com     tl99
77      Gavin Palmer   Male    1991-01-06     gavin.p91@email.com     gp91
79     Marcus Sutton   Male    1988-08-19    marcus.s88@yahoo.com     ms88
81      Colin Reeves   Male    1993-02-27     colin.r93@gmail.com     cr93
83       Dean Larson   Male    1994-11-04      dean.l94@email.com     dl94
85      Spencer Dean   Male    1987-10-15   spencer.d87@yahoo.com     sd87
89       Zane Harper   Male    1997-06-02      zane.h97@email.com     zh97
91      Grant Norris   Male    1992-12-18     grant.n92@yahoo.com     gn92
===========================================================================

Total : 38

- Male users that born >= 2000-12-31

In [91]:
# find male users that born >= 2000-12-31
above_twoth_male = male_user_df[male_user_df['Date of birth'] >= '2000-12-31']
print("Male user that born under >= 2000-12-31\n")
print(above_twoth_male)
# Number of male users that born >= 2000-12-31
print("="*75)
print(f"\nTotal : {above_twoth_male.shape[0]}")

Male user that born under >= 2000-12-31

         Full name Gender Date of birth                  Email Password
1    Daniel Carter   Male    2003-09-04   daniel.c03@yahoo.com     dc03
9      Jack Nelson   Male    2002-07-05     jack.n02@gmail.com     jn02
21     Logan Price   Male    2002-04-10    logan.p02@gmail.com     lp02
29   Andrew Butler   Male    2004-02-03   andrew.b04@email.com     ab04
31    Wyatt Foster   Male    2001-07-31    wyatt.f01@yahoo.com     wf01
35  Connor Griffin   Male    2003-03-06   connor.g03@email.com     cg03
73    Sean Spencer   Male    2002-10-01     sean.s02@yahoo.com     ss02
87  Tristan Newman   Male    2002-03-12  tristan.n02@gmail.com     tn02
===========================================================================

Total : 8

- Female users that born < 2000-12-31

In [92]:
# find female users that born < 2000-12-31
under_twoth_female = female_user_df[female_user_df['Date of birth'] < '2000-12-31']
print("Female user that born under < 2000-12-31\n")
print(under_twoth_female)
# Number of female users that born < 2000-12-31
print("="*75)
print(f"\nTotal : {under_twoth_female.shape[0]}")

Female user that born under < 2000-12-31

           Full name  Gender Date of birth                   Email Password
2      Olivia Turner  Female    1989-06-27    olivia.t89@email.com     ot89
8       Sophia Green  Female    1999-01-17    sophia.g99@email.com     sg99
10       Ella Parker  Female    1991-10-09      ella.p91@yahoo.com     ep91
12     Grace Collins  Female    2000-02-28     grace.c00@gmail.com     gc00
20       Aria Watson  Female    1996-07-29      aria.w96@email.com     aw96
22      Scarlett Cox  Female    1993-02-15  scarlett.c93@yahoo.com     sc93
28  Victoria Russell  Female    1989-08-06  victoria.r89@yahoo.com     vr89
30   Madison Simmons  Female    1995-11-25   madison.s95@gmail.com     ms95
34    Penelope Hayes  Female    1987-06-18  penelope.h87@yahoo.com     ph87
36      Lucy Wallace  Female    1994-10-22      lucy.w94@gmail.com     lw94
48      Alice Pierce  Female    1997-09-03     alice.p97@gmail.com     ap97
58   Madeline Hunter  Female    1999-02-18  madeline.h99@yahoo.com     mh99
66        Elena Shaw  Female    1998-11-13     elena.s98@gmail.com     es98
72       Faith Grant  Female    1995-04-14     faith.g95@gmail.com     fg95
74      Luna Hawkins  Female    1992-07-07      luna.h92@email.com     lh92
78        Jade Black  Female    2000-12-08      jade.b00@gmail.com     jb00
80     Tessa Gregory  Female    1996-03-11     tessa.g96@email.com     tg96
86       Brooke Carr  Female    1998-01-08    brooke.c98@email.com     bc98
88     Kylie Schultz  Female    1990-09-29     kylie.s90@yahoo.com     ks90
===========================================================================

Total : 19

- Female users that born >= 2000-12-31

In [93]:
# find female users that born >= 2000-12-31
above_twoth_female = female_user_df[female_user_df['Date of birth'] >= '2000-12-31']
print("Female user that born under >= 2000-12-31\n")
print(above_twoth_female)
# Number of female users that born >= 2000-12-31
print("="*75)
print(f"\nTotal : {above_twoth_female.shape[0]}")

Female user that born under >= 2000-12-31

          Full name  Gender Date of birth                  Email Password
4       Mia Bennett  Female    2001-03-08      mia.b01@yahoo.com     mb01
16      Lily Cooper  Female    2001-08-13     lily.c01@yahoo.com     lc01
18     Hannah Kelly  Female    2004-05-17   hannah.k04@gmail.com     hk04
26    Emily Sanders  Female    2003-10-28    emily.s03@email.com     es03
40     Stella Owens  Female    2002-09-16   stella.o02@yahoo.com     so02
42     Bella Knight  Female    2001-05-05    bella.k01@gmail.com     bk01
46  Sadie Armstrong  Female    2003-11-11    sadie.a03@yahoo.com     sa03
52       Eva Powell  Female    2002-12-19      eva.p02@yahoo.com     ep02
54       Clara Webb  Female    2001-04-01    clara.w01@gmail.com     cw01
56      Rose Tucker  Female    2003-06-07     rose.t03@email.com     rt03
62      Sophie Boyd  Female    2004-03-09   sophie.b04@email.com     sb04
64    Claire Warren  Female    2002-02-06   claire.w02@yahoo.com     cw02
68     Ruby Nichols  Female    2001-01-20     ruby.n01@email.com     rn01
82   Vanessa Little  Female    2003-07-30  vanessa.l03@yahoo.com     vl03
84      Hope Fuller  Female    2001-06-21     hope.f01@gmail.com     hf01
90      Molly Bates  Female    2004-05-23    molly.b04@gmail.com     mb04
===========================================================================

Total : 16